### ISSUE TITLE
Azure exporter metrics multiple dimensions not working as expected

### ISSUE THREAD

**Issue by mtrin** [grafana/agent#6637]
### What's wrong?

Referencing to previously closed issue https://github.com/grafana/agent/issues/5411 FYI @kgeckhart

Either I'm doing something wrong or the implementation hasn't worked.

Currently, I still get the same error even when `validate_dimensions	   = false`  and I don't get metrics

### Steps to reproduce

I updated to the latest agent with updated configs and it still doesn't seem to allow me to have a single, or fewer jobs.
It's like the final call to `management.azure.com` api still doesn't have the `ValidateDimensions=false`
the expected call should be:
`GET https://management.azure.com/subscriptions/<foo>/resourceGroups/<xyz>/providers/Microsoft.Network/applicationGateways/<xyz>/providers/Microsoft.Insights/metrics?&ValidateDimensions=false`
Which in my understanding, would not produce any error.

### Software version

v0.40.2

### Configuration

```text
prometheus.exporter.azure "appgateway_metrics" {
	subscriptions          = ["foo"]
	resource_type          = "Microsoft.Network/applicationGateways"
	validate_dimensions	   = false
	regions				   = ["australiaeast"] 
	// also tried resource_graph_query_filter	   = "where tags['monitored'] == 'true'" to test without regions set
	included_resource_tags = [
		"CostCode",
		"Environment",
		"Owner",
		"Author",
		"ManagedBy",
	]
	included_dimensions = [
		"BackendHttpSetting", 
		"BackendPool", 
		"BackendServer",
		"BackendSettingsPool",
		"HttpStatusGroup",
		"Listener",
		"RuleGroup", 
		"RuleId",
	]
	metrics             = [
		"ApplicationGatewayTotalTime",
		"AvgRequestCountPerHealthyHost",
		"BackendConnectTime",
		"BackendFirstByteResponseTime",
		"BackendLastByteResponseTime",
		"BackendResponseStatus",
		"ClientRtt",
		"FailedRequests",
		"HealthyHostCount",
		"Throughput",
		"TotalRequests",
		"UnhealthyHostCount",
	]
	timespan = "PT1M"
}
```

### Logs

```text
GET https://management.azure.com/subscriptions/<foo>/resourceGroups/<xyz>/providers/Microsoft.Network/applicationGateways/<xyz>/providers/Microsoft.Insights/metrics
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: BadRequest
--------------------------------------------------------------------------------
{
  "code": "BadRequest",
  "message": "Metric: AvgRequestCountPerHealthyHost does not support requested dimension combination: listener, supported ones are: BackendSettingsPool, TraceId: {9844da31-b35d-44ba-b9b5-97d56fb43a09}"
}
--------------------------------------------------------------------------------
if I remove AvgRequestCountPerHealthyHost, it will error out in the next one and so on
```

**Comment by kgeckhart** [comment]
@mtrin so I scanned the code and nothing obvious stood out as far as why this is behaving this way. I did notice this bug, https://github.com/grafana/agent/blob/448b2456b1d7f9b6fd5e9566e53cf893587b3e12/internal/static/integrations/azure_exporter/azure_exporter.go#L84-L84, where subscription scope is only enabled when more than 2 or more regions are specified 🤦 . I'm happy to fix it or if you want to so you can get a commit go for it!

Could you humor me and try putting two regions in to help narrow it down between the two implementations?

**Comment by kgeckhart** [comment]
I was going mad trying to figure out what's going on because based on everything I could see the value was being sent to the API and sure enough it is and Azure's API appears to be broken,

`az rest --method get --url 'https://management.azure.com/subscriptions/<redacted>/providers/Microsoft.Insights/metrics?api-version=2021-05-01&%24filter=Microsoft.ResourceId+eq+%27%2A%27+and+ApiName+eq+%27%2A%27+and+TransactionType+eq+%27%2A%27&AutoAdjustTimegrain=true&ValidateDimensions=false&interval=PT1H&metricnames=Availability%2CBlobCapacity%2CBlobCount%2CContainerCount%2CEgress%2CIndexCapacity%2CIngress%2CSuccessE2ELatency%2CSuccessServerLatency%2CTransactions&metricnamespace=Microsoft.Storage%2FstorageAccounts%2FblobServices&region=global&resultType=Data&timespan=PT1H&top=100000000'`

results in
`Bad Request({"error":{"additionalInfo":[{"type":"string","info":"TraceId={}"},{"type":"string","info":"DateTime=2024-03-18T17:53:39.3769458Z"},{"type":"string","info":"ExceptionType=Microsoft.Online.Metrics.MetricsMP.Utilities.RPRequestFormatException"}],"code":"BadRequest","message":"Metric: BlobCapacity does not support requested dimension combination: apiname, supported ones are: BlobType,Tier, TraceId: {<redacted>}"}})`

The API docs for this api version even show it's valid https://learn.microsoft.com/en-us/rest/api/monitor/metrics/list-at-subscription-scope?view=rest-monitor-2021-05-01&tabs=HTTP

**Comment by kgeckhart** [comment]
We opened an internal support issue with azure and are currently awaiting response

**Comment by mtrin** [comment]
hey @kgeckhart thanks a lot for looking into this, I've been meaning to respond with a test but I can see you have gone further. I ended up testing 
I also almost went mad and even tried to use webdevops azure-metrics-exporter and to my surprise I was getting the same error
Calling that via postman it's like that validation flag is making no effect on az api 🤦‍♂️

**Comment by kgeckhart** [comment]
Sorry to put you through that as well! We are still working through azure support and 🤞 they fix it soon. Both of these were really exciting features and it would be really unfortunate if they couldn't be used together.

**Comment by kgeckhart** [comment]
@mtrin we got confirmation from azure that this should be fixed now. I tested and it seems to be true. Can you give it a shot?

**Comment by mtrin** [comment]
@kgeckhart thanks! give me a couple of days or so I'll test it for you

**Comment by mtrin** [comment]
@kgeckhart perfect, it works! 
heads up tho that it still fails with some of their documentation being wrong or api broken, for example for the BlockedCount metric. So need to remove problematic metrics.

```
RESPONSE 400: 400 Bad Request
ERROR CODE: BadRequest
--------------------------------------------------------------------------------
{
  "code": "BadRequest",
  "message": "Failed to find metric configuration for provider: Microsoft.Network, resource Type: applicationGateways, metric: BlockedCount, Valid metrics: Throughput,UnhealthyHostCount,HealthyHostCount,TotalRequests,AvgRequestCountPerHealthyHost,FailedRequests,ResponseStatus,CurrentConnections,NewConnectionsPerSecond,CapacityUnits,FixedBillableCapacityUnits,EstimatedBilledCapacityUnits,ComputeUnits,BackendResponseStatus,TlsProtocol,BytesSent,BytesReceived,ClientRtt,ApplicationGatewayTotalTime,BackendConnectTime,BackendFirstByteResponseTime,BackendLastByteResponseTime,AzwafTotalRequests,AzwafCustomRule,AzwafSecRule,AzwafBotProtection"
}
--------------------------------------------------------------------------------
```
which for me isn't an issue, looks like Azwaf ones can replace it.

Thanks a lot for your help
